### ISSUE TITLE
zimu - Lack of events for critical arithmetic parameters

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-bond-judging#33]
zimu

medium

# Lack of events for critical arithmetic parameters

## Summary
Function `BondBaseSDA.setDefaults` sets critical arithmetic parameters for bond market. But it has no event emitted, it is difficult to track these critical changes off-chain.

## Vulnerability Detail
In `bases/BondBaseSDA`, critical parameters are set and changed in function `BondBaseSDA.setDefaults` for bond market.
![image](https://user-images.githubusercontent.com/112361239/201988699-b740b31b-e6d1-4bd8-b3da-2fb9bc7c68bd.png)

However, no event is emitted, and it is difficult to track these critical changes off-chain.  Both Users and Issuers would possibly be unware of  these changes.

## Impact
Both Users and Issuers would possibly be unware of  critical changes on bond market.

## Code Snippet
https://github.com/sherlock-audit/2022-11-bond/blob/main/src/bases/BondBaseSDA.sol#L348-L356

## Tool used
Manual Review

## Recommendation
Add an event in `BondBaseSDA.setDefaults` to report critical arithmetic changes.

**Comment by Evert0x** [comment]
Downgrading to low severity.
