### ISSUE TITLE
bin2chen - findMarketFor() missing check minAmountOut_

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-bond-judging#38]
bin2chen

medium

# findMarketFor() missing check minAmountOut_

## Summary
BondAggregator#findMarketFor() minAmountOut_ does not actually take effect，may return a market's "payout" smaller than minAmountOut_ , Causes users to waste gas calls to purchase

## Vulnerability Detail
BondAggregator#findMarketFor() has check minAmountOut_ <= maxPayout
but the actual "payout" by "amountIn_" no check  greater than minAmountOut_
```solidity
    function findMarketFor(
        address payout_,
        address quote_,
        uint256 amountIn_,
        uint256 minAmountOut_,
        uint256 maxExpiry_
    ) external view returns (uint256) {
...
            if (expiry <= maxExpiry_) {
                payouts[i] = minAmountOut_ <= maxPayout
                    ? payoutFor(amountIn_, ids[i], address(0))
                    : 0;

                if (payouts[i] > highestOut) {//****@audit not check payouts[i] >= minAmountOut_******//
                    highestOut = payouts[i];
                    id = ids[i];
                }
            }

```

## Impact

The user gets the optimal market through BondAggregator#findMarketFor(), but incorrectly returns a market smaller than minAmountOut_, and the call to purchase must fail, resulting in wasted gas

## Code Snippet

https://github.com/sherlock-audit/2022-11-bond/blob/main/src/BondAggregator.sol#L248

## Tool used

Manual Review

## Recommendation
```solidity
    function findMarketFor(
        address payout_,
        address quote_,
        uint256 amountIn_,
        uint256 minAmountOut_,
        uint256 maxExpiry_
    ) external view returns (uint256) {
...
            if (expiry <= maxExpiry_) {
                payouts[i] = minAmountOut_ <= maxPayout
                    ? payoutFor(amountIn_, ids[i], address(0))
                    : 0;

-               if (payouts[i] > highestOut) {
+               if (payouts[i] >= minAmountOut_ && payouts[i] > highestOut) {
                    highestOut = payouts[i];
                    id = ids[i];
                }
            }

```

**Comment by Evert0x** [comment]
Downgrading to low, considering the impact is wasted gas
